###
GET http://localhost:3000/api/contacts
###
GET http://localhost:3000/api/contacts/contacturl

###
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
   "name": "Contact name",
   "url": "contacturl",
   "email": "contact@email.com",
   "phone": "0000000000",
   "photo": "contact.jpg"
}

###
PUT http://localhost:3000/api/contacts/contacturl
Content-Type: application/json

{
   "name": "Contact new name",
   "url": "contacturl",
   "email": "contact@email.com",
   "phone": "0000000000",
   "photo": "contact.jpg"
}

###
DELETE http://localhost:3000/api/contacts/contacturl

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/username

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
   "name": "user name",
   "email": "user@email.com",
   "password": "password",
   "username": "username"
}

### 
PUT http://localhost:3000/api/users/username
Content-Type: application/json

{
   "name": "new user name",
   "email": "user@email.com",
   "password": "password",
   "username": "username"
}

###
DELETE http://localhost:3000/api/users/username


###
POST http://localhost:3000/signin
Content-Type: application/json

{
   "username": "newUsername",
   "password": "newPassword"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
   "name": "New User",
   "email": "newUser@email.com",
   "password": "newPassword",
   "username": "newUsername"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMjk4YWZhZDY1NDkzMDUwYzk1OTY5ZSIsInVzZXJuYW1lIjoibmV3VXNlcm5hbWUiLCJpYXQiOjE1OTY1NjM2MzEsImV4cCI6MTU5NjY1MDAzMX0.KIfRd93f4bqQeZdsTeCnXzP-R-HsNUvKsC7e52YTsqs

###
DELETE http://localhost:3000/api/users/newUsername